main: eu.decentsoftware.holograms.plugin.DecentHologramsPlugin
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - ProtocolLib
name: DecentHolograms
description: ${description}
version: ${version}
author: d0by